app = "your-medical-inspector-app"
primary_region = "Eu"  # Virginia region

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  
[mounts]
  source = "data"
  destination = "/app/data"

[env]
  API_KEY = "3tMsIHPXAW6pUTPWTVWO"

[vm]
  memory = "1024"  # Minimum required for OCR